var init={swiper:function(){var width=$(window).width();var navigation=function(elem){var parent=$(elem).parents('.container');return{nextEl:$('.swiper-button-next',parent),prevEl:$('.swiper-button-prev',parent),}}
new Swiper('#slides-main',{spaceBetween:0,autoplay:{delay:5000,},autoHeight:true,effect:'fade',roundLengths:true,navigation:navigation('#slides-main'),});new Swiper('#swiper-reviews',{spaceBetween:30,slidesPerView:1,autoHeight:true,roundLengths:true,navigation:navigation('#swiper-reviews'),});},mobileMenu:function(){$('#mobile-menu').menu();$('#mobile-menu-close').on('click',function(){$('#mobile-menu').menu('close');})
$('#mobile-menu-toggle').on('click',function(e){e.preventDefault();$('#mobile-menu').menu('open');})
$(".mobile-body .scrollTo").on('click',function(){$('#mobile-menu').menu('close');})},modal:function(){$('a[data-modal]').click(function(event){var text_default=$(this).data('modal-title')||'Укажите контакты';$('#modal-title').text(text_default)
$(this).modal({fadeDuration:250});return false;});},magnific:function(){$('.gallery').each(function(){$(this).magnificPopup({delegate:'.image',type:'image',gallery:{enabled:true},});});},video:function(){$('.popup-video').magnificPopup({disableOn:false,type:'iframe',mainClass:'mfp-fade',removalDelay:160,preloader:false,fixedContentPos:false});},wow:function(){$('.wow-delay').each(function(){var delay=0;$('.wow',this).each(function(){delay+=0.1;if(delay>1)delay=0;$(this).attr('data-wow-delay',delay+'s');})});new WOW().init();},onload:function(){var ready=false;var load=function(){if(ready)return;ready=true;clearTimeout(timer);$('body').addClass('loaded');init.wow();}
var timer=setTimeout(function(){load();},5000);window.addEventListener('load',function(){load();});},form:function(open_page){$("input[name='phone']").inputmask("+38 (999) 999 99 99",{clearMaskOnLostFocus:true});$('form').submit(function(e){e.preventDefault();var form=$(this);$('button',form).css({opacity:0.5}).attr('disabled','');$.post('mail/send.php',$(this).serializeArray(),function(json){$('button',form).css({opacity:1}).removeAttr('disabled');if(json.success){if(open_page){window.location=open_page;}else{$('#modal-success').modal({fadeDuration:250});setTimeout(function(){$('input,textarea',form).not('[type="hidden"]').val('');$.modal.close();},3000);}}},'json');})},faq:function(){$('.e_faq').each(function(){var item=$(this);var body=$('.e_faq-body',item);$('.e_faq-header',item).on('click',function(){if(body.is(':visible')){body.slideUp(200);item.removeClass('open')}else{body.slideDown(200);item.addClass('open');}})})},more:function(){$('.e_more').each(function(){var read=$('.e_more-read',this);var body=$('.e_more-body',this);read.on('click',function(e){e.preventDefault();if(body.is(':visible')){body.slideUp(200);read.text('Развернуть');}else{body.slideDown(200);read.text('Свернуть');}})})},time:function(elem,date){var timeend=new Date(date);function time(){var today=new Date();today=Math.floor((timeend-today)/1000);var tsec=today%60;today=Math.floor(today/60);if(tsec<10)tsec='0'+tsec;var tmin=today%60;today=Math.floor(today/60);if(tmin<10)tmin='0'+tmin;var thour=today%24;today=Math.floor(today/24);today=('0'+today).slice(-2);tsec=('0'+tsec).slice(-2);tmin=('0'+tmin).slice(-2);thour=('0'+thour).slice(-2);$('.day',elem).text(today);$('.hour',elem).text(thour);$('.min',elem).text(tmin);$('.sec',elem).text(tsec);}time();setInterval(time,1000)},scrollTo:function(pushHistory){$(".scrollTo").click(function(e){e.preventDefault();$.modal.close();var id=$(this).attr('href')||$(this).data('modal');var ps=$(id).offset().top;if(pushHistory){if(history.pushState){history.pushState(null,null,id);}else{location.hash=id;}}$('html, body').animate({scrollTop:ps-20},Math.max(500,Math.round(ps*0.2)));});},tabs:function(){$('.tabs').each(function(){var links=$('.tabs-link',this);var content=$('.tabs-content',this);links.on('click',function(e){e.preventDefault();links.removeClass('active');$(this).addClass('active');var target=$(this).attr('href');content.removeClass('active')
$(target).addClass('active')})})},fluid:function(){function resize(){var width=$(window).width();$('.fluid-right').each(function(){var offset=$(this).offset();$(this).width(width-offset.left);});}$(window).resize(resize);resize();},sticker:function(elem){elem.sticky({topSpacing:0});},calc:function(){var box=$('.b-calc');var nums=$('.form-utter',box);var items=$('.b-calc--make',box);var game=$('.calc-type-game',box)
nums.each(function(){var num=$(this);var min=parseInt(num.data('min'));var max=parseInt(num.data('max'));num.focusout(function(){var val=parseInt(num.val());val=isNaN(val)?1:val;val=Math.min(max,Math.max(min,val));num.val(val);})})
$(".calc-range-hours").ionRangeSlider({label:false,grid:true,min:2,max:5,step:1,values:['2 часа','3 часа','4 часа','5 часов']});$(".calc-range-bullets").ionRangeSlider({label:false,grid:true,min:100,max:1000,step:100,values:['100 шт','200 шт','300 шт','400 шт','500 шт','600 шт','700 шт','800 шт','900 шт','1000 шт']});items.hide();game.on('change',function(){var type=$(this).val();items.hide();$('.'+type,box).show();})
}}
$(function(){var isPageSpeed=/Google Page Speed Insights/.test(navigator.userAgent);if(isPageSpeed)return;init.magnific();init.video();init.swiper();init.modal();init.mobileMenu();init.form();init.faq();init.more();init.scrollTo(false);init.tabs();init.calc();$('select').niceSelect();init.sticker($('#sticker'));})
init.onload();
